name: Publish package to the Maven Central Repository
on:
    release:
        types: [created]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Maven Central Repository
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'temurin'
                  server-id: ossrh
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
                  gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

            - id: get_version
              uses: battila7/get-version-action@v2
            - name: Update package version
              run: mvn --projects mapstruct-wither-support versions:set -DnewVersion=${{ steps.get_version.outputs.version-without-v }}

            - name: Publish to GitHub Packages
              run: mvn --projects mapstruct-wither-support --batch-mode -PgithubDeploy -DskipTests deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish package Central
              run: mvn --projects mapstruct-wither-support --batch-mode -PossrhDeploy -DskipTests deploy
              env:
                  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
                  MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}